{% set name = "in-n-out" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 43cde2b7de981d41a6d70618a2b7bd989481095922a53ead4dc75f2bbd5dffea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  imports:
    - in_n_out
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/in-n-out
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python dependency injection you can taste
  dev_url: https://github.com/tlambert03/in-n-out

extra:
  recipe-maintainers:
    - tlambert03
