{% set name = "in-n-out" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8162af8787e682eb4b36d047f914199d80f1124e3a41420cd53de680e7d0a254

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8

test:
  imports:
    - in_n_out
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/in-n-out
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python dependency injection you can taste
  dev_url: https://github.com/tlambert03/in-n-out

extra:
  recipe-maintainers:
    - tlambert03
